'use strict';
import bcrypt from 'bcrypt';

/** @type {import('sequelize-cli').Migration} */
export async function up(queryInterface, Sequelize) {
    const hashedPassword = await bcrypt.hash('123456', 10);
    return queryInterface.bulkInsert('staffs', [
        {
            username: 'staff1',
            password: hashedPassword,
            first_name: 'Minh',
            last_name: 'Nguyễn',
            avatar: null,
            phone: '0900000001',
            email: 'staff1@hotel.com',
            address: 'HCM',
            role: 'staff',
            hotel_id: 1,
        },
        {
            username: 'admin1',
            password: hashedPassword,
            first_name: 'Hải',
            last_name: 'Trần',
            avatar: null,
            phone: '0900000002',
            email: 'admin1@hotel.com',
            address: 'HCM',
            role: 'admin',
            hotel_id: 1,
        },
        {
            username: 'staff2',
            password: hashedPassword,
            first_name: 'Linh',
            last_name: 'Lê',
            avatar: null,
            phone: '0900000003',
            email: 'staff2@hotel.com',
            address: 'Hà Nội',
            role: 'staff',
            hotel_id: 2,
        },
        {
            username: 'admin2',
            password: hashedPassword,
            first_name: 'Tú',
            last_name: 'Phạm',
            avatar: null,
            phone: '0900000004',
            email: 'admin2@hotel.com',
            address: 'Hà Nội',
            role: 'admin',
            hotel_id: 2,
        },
        {
            username: 'staff3',
            password: hashedPassword,
            first_name: 'Đức',
            last_name: 'Vũ',
            avatar: null,
            phone: '0900000005',
            email: 'staff3@hotel.com',
            address: 'Đà Nẵng',
            role: 'staff',
            hotel_id: 3,
        },
        {
            username: 'admin3',
            password: hashedPassword,
            first_name: 'Lan',
            last_name: 'Ngô',
            avatar: null,
            phone: '0900000006',
            email: 'admin3@hotel.com',
            address: 'Đà Nẵng',
            role: 'admin',
            hotel_id: 3,
        },
        {
            username: 'staff4',
            password: hashedPassword,
            first_name: 'Thảo',
            last_name: 'Bùi',
            avatar: null,
            phone: '0900000007',
            email: 'staff4@hotel.com',
            address: 'Huế',
            role: 'staff',
            hotel_id: 4,
        },
        {
            username: 'admin4',
            password: hashedPassword,
            first_name: 'Khánh',
            last_name: 'Hoàng',
            avatar: null,
            phone: '0900000008',
            email: 'admin4@hotel.com',
            address: 'Huế',
            role: 'admin',
            hotel_id: 4,
        },
        {
            username: 'staff5',
            password: hashedPassword,
            first_name: 'My',
            last_name: 'Đinh',
            avatar: null,
            phone: '0900000009',
            email: 'staff5@hotel.com',
            address: 'Đà Lạt',
            role: 'staff',
            hotel_id: 5,
        },
        {
            username: 'admin5',
            password: hashedPassword,
            first_name: 'Sơn',
            last_name: 'Trương',
            avatar: null,
            phone: '0900000010',
            email: 'admin5@hotel.com',
            address: 'Đà Lạt',
            role: 'admin',
            hotel_id: 5,
        },
    ]);
}
export async function down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('staffs', null, {});
}
